# Permalinks
permalink:           pretty

# Setup
title:               BlancNote
tagline:             curiouser and curiouser...
url:                 http://blancnote.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Pankaj Ghosh
  url:               https://twitter.com/rabbitholing
  email:             pankajghosh@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/pankajghosh/pankajghosh.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
